version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MarketDB
    ports:
      - "5432:5432"

  web:
    build:
      context: ./MarketAssetPriceService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=MarketDB;Username=postgres;Password=password

  ef:
    build:
      context: ./MarketAssetPriceService
      dockerfile: Dockerfile
      target: efcore
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=MarketDB;Username=postgres;Password=password
    entrypoint: ["dotnet", "ef", "database", "update"]
